name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Project Files
        run: ls -la

      - name: Build Successful
        run: echo "Online Shopping Project Build Successful"

      - name: Test Successful
        run: echo "Login Page Tested Successfully"
